
# POSTGRES_SQL_USERNAME: root
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: Aboard$789
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: mbs

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#JWT TOKEN
JWT_TOKEN_SECRET: 66546A576E5A7234753778214125442A472D4B614E645267556B587032733576

JWT_ACCESS_TOKEN_DURATION_MINUTE: 15 
JWT_ACCESS_TOKEN_DURATION_SECOND: 9000 
JWT_REFRESH_TOKEN_DURATION_DAY: 7 
JWT_REFRESH_TOKEN_DURATION_SECOND: 604800  

JWT_ACCESS_COOKIE_NAME: access_token
JWT_REFRESH_COOKIE_NAME: refresh_token